### ISSUE TITLE
GeometryType: ENUM or CLASS?

### ISSUE THREAD

**Issue by jotoh98** [jotoh98/treasureHunt#10]
The decision unfolds as follows:

#9 proposes a change to the `GeometryItem`'s implementation as an enumeration.

`GeometryType` may be a **enumeration** getting translated by each `UIRenderer` on its own. This may cause some DRY issues regarding code repetition and maintainability. But it reduces the code written to inform these renderers about what to draw and how to represent the `GeometryItem`s.

E.g.: When we want to introduce changes to the enum `STANDARD`'s color representation, we need to change it in all UI Generators.

As a **class**, `GeometryItem` holds a configuration in the form of the fields values combination.
With static constructor methods, we reduce the written code in each "end user"'s implementation.
`public static GeometryType STANDARD() {
    return new GeometryType(true, Color.black, "");
}`
Furthermore, when we need a certain configuration for a custom strategy implementation, we simply instantiate a new `GeometryType` object and change predefined values.

**Comment by DorianRec** [comment]
Another disadvantage of the class design is, that the Renderer cannot use custom representations of these GeometryItems. They must use the Settings written in these GeometryObjects since they does not know, what these Objects really are.

Another Advantage of the enumeration design is:
Yes, for every new enum, we have to adapt every UIRenderer-class,
but the case that we got a new enum will be very rare.

**Comment by jotoh98** [comment]
Agreed to divide GameLogic and RenderLogic into enum GeometryType and class GeometryStyle
