### ISSUE TITLE
GameEngine provides original hints

### ISSUE THREAD

**Issue by jotoh98** [jotoh98/treasureHunt#173]
Searcher.move gets the original object and is able to manipulate it.
Fix in:
* [ ] Treasure
* [ ] SearchPath
* [ ] Hints

**Comment by 1-alex98** [comment]
Use kyro make a deep copy

**Comment by DorianRec** [comment]
> Use kyro make a deep copy

Got a better idea by making Treasure, SearchPath and Hints unchangable after initialized,
if one asks for them GeometryItems, new ones got created, such Treasure, SearchPath and Hints are effectively not changeable.
Deep copy's 're bad design in my mind.

**Comment by DorianRec** [comment]
To fix this:
* Hints and SearchPaths has to be instantiated with copies, The copies could be created in the constructor.
* Hints and SearchPaths has to return copies of them objects in the getter methods.
* We have to remove the methods `void addPoint(Point point)`,`void addPoint(double x, double y)`, `addAdditionalItem(GeometryItem<?> geometryItem)`, since they allow modification of the SearchPaths.
* The **arbitrary** Objects in the GeometryItem must be clonable/copyable. Thus, we should make it Geometry and define a lightwighter class for ImageItem and other possible Items ..

**Comment by DorianRec** [comment]
I think, we have to ignore these issue and unify on the rule that Searcher/Hider are not modify SearchPath and Hints. Solving this is only possible by either
* creating tons of copies or
* making SearchPath/Hints unchangeable.

The first will mess up our runtime (unnecessary in my mind).
The second is pretty hard to implement, since SearchPath/Hints contain (complex) structures, which we **have to** clone, to make them "unchangeable". Thus, we have to clone these structures (which will again mess up our runtime), or we make SearchPath/Hints lightweight and only contain primitive types, which is unrealistic, since they contain Geometrys.
